name: Playwright Tests and Email Notification

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run Playwright Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # 👇 PERINTAH SPESIFIK ANDA DIGUNAKAN DI SINI 👇
      - name: Run Playwright tests
        run: npx playwright test tests/Record-Attendance/ | tee test-summary.txt

      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      
      - name: Read test summary
        id: test_summary
        if: always()
        run: echo "summary=$(cat test-summary.txt)" >> $GITHUB_ENV
        
      - name: Send email notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}

          subject: 'Hasil Tes Playwright: ${{ job.status }} - Repositori ${{ github.repository }}'
          
          body: |
            Tes otomatis telah selesai dijalankan.

            Repositori: ${{ github.repository }}
            Pemicu Event: ${{ github.event_name }}
            Status Tes: ${{ job.status }}
            Dijalankan oleh: ${{ github.actor }}
            Commit: "${{ github.event.head_commit.message }}"

            Anda bisa melihat detail log dan mengunduh laporan artifact di link berikut:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            ---
            **Ringkasan Hasil Tes:**
            ```
            ${{ env.summary }}
            ```
          to: anggatrianto180@gmail.com
          from: GitHub Actions <no-reply@github.com>